# Generated by Django 2.2.12 on 2020-05-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonclubapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='resourceDescription',
        ),
        migrations.AddField(
            model_name='event',
            name='eventDescription',
            field=models.TextField(null=True),
        ),
    ]
